class PipelineEvents:
    # STT
    STT_STARTED = "PIPELINE.STT_STARTED"
    STT_FINISHED = "PIPELINE.STT_FINISHED"
    TRANSCRIPT_UPDATED = "PIPELINE.TRANSCRIPT_UPDATED"  # Fired on partials
    TRANSCRIPT_FINAL = "PIPELINE.TRANSCRIPT_FINAL"      # Fired on final utterance
    
    # Intent
    INTENT_DETECTED = "PIPELINE.INTENT_DETECTED"
    
    # LLM
    LLM_STARTED = "PIPELINE.LLM_STARTED"
    TOKEN_RECEIVED = "PIPELINE.TOKEN_RECEIVED"
    SENTENCE_COMPLETED = "PIPELINE.SENTENCE_COMPLETED"
    LLM_FINISHED = "PIPELINE.LLM_FINISHED"
    
    # TTS
    TTS_STARTED = "PIPELINE.TTS_STARTED"
    AUDIO_PLAYING = "PIPELINE.AUDIO_PLAYING"
    TTS_FINISHED = "PIPELINE.TTS_FINISHED"
    
    # System
    ERROR = "PIPELINE.ERROR"
    METRIC_UPDATED = "PIPELINE.METRIC_UPDATED"
