from enum import Enum

class SystemState(Enum):
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    TRANSCRIBING = "TRANSCRIBING"
    UNDERSTANDING = "UNDERSTANDING"
    GENERATING = "GENERATING"
    SPEAKING = "SPEAKING"
    EXECUTING = "EXECUTING"
    INTERRUPTED = "INTERRUPTED"
    ERROR = "ERROR"
